### ISSUE TITLE
avm_fritz_toolbox renamed to fbtr64toolbox

### ISSUE THREAD

**Issue by MarcusRoeckrath** [sky321/fritz_TR-064#1]
Hi,

yesterday I renamed the eisfair package avm_fritz_toolbox to fbtr64toolbox and the script itself from avm-fritz-toolbox.sh to fbtr64toolbox.sh releasing newest version today which has enhancements compared to the latest release under the old package name.

The old package is not available any more.

URL of official eisfair repository:

https://www.pack-eis.de/index.php?p=fbtr64toolbox

Marcus

**Comment by MarcusRoeckrath** [comment]
Attached newest release 2.9.2 of eisfair package fbtr64toolbox.tar.bz2 containing script fbtr64toolbox 2.3.1.

**Comment by MarcusRoeckrath** [comment]
Hi,

please correct the issue described above.

Thanks.

Marcus (author of fbtr64toolbox former named avm-fritz-toolbox)

**Comment by sky321** [comment]
Sorry for been so late on this topic. Will correct the url and take the old script offline as fast as possible.

**Comment by MarcusRoeckrath** [comment]
Many thanks.
